### ISSUE TITLE
dbc_dark dropdown searchable text input change

### ISSUE THREAD

**Issue by enkokoro** [AnnMarieW/HelloDash#7]
For the dbc_dark version of the dropdown, when you try to search for something, the input text is black and therefore not visible. If you add the following to the dark version css, it fixes the issue for the dark theme.

.Select input{
  color:white;
}

**Comment by AnnMarieW** [comment]
Nice catch!  I'll fix that. 
Thanks for the feedback :+1:

**Comment by AnnMarieW** [comment]
This is live now.  Thanks again.
